// Theresa
export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const UPDATE_CURRENT_RECIPE = "UPDATE_CURRENT_RECIPE";
export const UPDATE_FAVORITE_RECIPES = "UPDATE_FAVORITE_RECIPES";

